// MUTATIONS
export const USER_NAME_CHANGED = 'USER_NAME_CHANGED';
export const USER_EMAIL_CHANGED = 'USER_EMAIL_CHANGED';
// auth
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';


// ACTIONS
