// user
export const USER_NAME_CHANGED = 'USER_NAME_CHANGED';
export const USER_EMAIL_CHANGED = 'USER_EMAIL_CHANGED';
// auth
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
// qr
export const QR_SIGN_UP_REQUEST = 'QR_SIGN_UP_REQUEST';
export const QR_SIGN_UP_REQUEST_FAILED = 'QR_SIGN_UP_REQUEST_FAILED';
export const QR_SIGN_UP_REQUEST_SUCCEED = 'QR_SIGN_UP_REQUEST_SUCCEED';
export const QR_SIGN_IN_REQUEST = 'QR_SIGN_IN_REQUEST';
export const QR_SIGN_IN_REQUEST_SUCCEED = 'QR_SIGN_IN_REQUEST_SUCCEED';
export const QR_SIGN_IN_REQUEST_FAILED = 'QR_SIGN_IN_REQUEST_FAILED';
export const SIGN_IN_SESSION_STATE_INITIALIZED = 'SIGN_IN_SESSION_STATE_INITIALIZED';
export const SIGN_UP_SESSION_STATE_INITIALIZED = 'SIGN_UP_SESSION_STATE_INITIALIZED';
// auth
export const VERIFIED_ME_SIGN_IN_REQUEST = 'VERIFIED_ME_SIGN_IN_REQUEST';
export const VERIFIED_ME_SIGN_IN_REQUEST_FAILED = 'VERIFIED_ME_SIGN_IN_REQUEST_FAILED';
export const VERIFIED_ME_SIGN_IN_REQUEST_SUCCEED = 'VERIFIED_ME_SIGN_IN_REQUEST_SUCCEED';
export const VERIFIED_ME_SIGN_UP_REQUEST = 'VERIFIED_ME_SIGN_UP_REQUEST';
export const VERIFIED_ME_SIGN_UP_REQUEST_FAILED = 'VERIFIED_ME_SIGN_UP_REQUEST_FAILED';
export const VERIFIED_ME_SIGN_UP_REQUEST_SUCCEED = 'VERIFIED_ME_SIGN_UP_REQUEST_SUCCEED';
// user
export const USER_DATA_REQUEST = 'USER_DATA_REQUEST';
export const USER_DATA_REQUEST_SUCCEED = 'USER_DATA_REQUEST_SUCCEED';
export const USER_DATA_REQUEST_FAILED = 'USER_DATA_REQUEST_FAILED';
