// qr
export const QR_SIGN_IN_REQUEST = 'QR_SIGN_IN_REQUEST';
export const QR_SIGN_IN_REQUEST_SUCCEED = 'QR_SIGN_IN_REQUEST_SUCCEED';
export const QR_SIGN_IN_REQUEST_FAILED = 'QR_SIGN_IN_REQUEST_FAILED';
// auth
export const AUTHORIZE_URL_REQUEST = 'AUTHORIZE_URL_REQUEST';
export const AUTHORIZE_URL_REQUEST_SUCCEED = 'AUTHORIZE_URL_REQUEST_SUCCEED';
export const AUTHORIZE_URL_REQUEST_FAILED = 'AUTHORIZE_URL_REQUEST_FAILED';
// user
export const USER_DATA_REQUEST = 'USER_DATA_REQUEST';
export const USER_DATA_REQUEST_SUCCEED = 'USER_DATA_REQUEST_SUCCEED';
export const USER_DATA_REQUEST_FAILED = 'USER_DATA_REQUEST_FAILED';
